### ISSUE TITLE
apisix对etcd去集群问题

### ISSUE THREAD

**Issue by 1026197530** [iresty/ingress-controller#5]
我测试apisix对etcd集群的支持情况，发现有点问题。我的测试方法是：先逐一的把etcd集群的节点杀掉，每杀掉一个就看一些dashboard。只有把3个etcd集群中的节点都杀掉时，dashboard才开始报错。但是，当我把etcd节点启动其中部分节点时，dashboard始终是去连一个我没有启动的etcd节点，而不会去尝试连接我已经启动的etcd节点。

**Comment by membphis** [comment]
please use English in public channel. 

It is a bug of resty-etcd: https://github.com/api7/lua-resty-etcd/issues/55

**Comment by gxthrj** [comment]
We provide ingress controller using apisix for k8s here.
It is a bug of resty-etcd: https://github.com/api7/lua-resty-etcd/issues/55
